---
- name: Play A
  hosts: localhost
  gather_facts: false
  vars: 
    device: "Router"
    type: "Cisco"
    ios: "ISR"
  tasks:
    - name: Print Hello message
      debug:
        msg: "Hello World!!!!"
    - name: Print Device
      debug:
        msg: "Device {{ device }}, Type of device is {{ type }} and its IOS is {{ ios }}."